// examples/next-ts/pages/carousel.tsx
import * as carousel from "@zag-js/carousel"
import { normalizeProps, useMachine } from "@zag-js/react"
import { carouselControls, carouselData } from "@zag-js/shared"
import { useId } from "react"
import { StateVisualizer } from "../components/state-visualizer"
import { Toolbar } from "../components/toolbar"
import { useControls } from "../hooks/use-controls"

export default function Page() {
  const controls = useControls(carouselControls)

  const service = useMachine(carousel.machine, {
    id: useId(),
    slideCount: carouselData.length,
    ...controls.context,
  })

  const api = carousel.connect(service, normalizeProps)

  return (
    <>
      <main className="carousel">
        <div {...api.getRootProps()}>
          <button onClick={() => api.scrollToIndex(4)}>Scroll to 4</button>
          <div {...api.getControlProps()}>
            <button {...api.getAutoplayTriggerProps()}>{api.isPlaying ? "Stop" : "Play"}</button>
            <div className="carousel-spacer" />
            <button {...api.getPrevTriggerProps()}>Prev</button>
            <button {...api.getNextTriggerProps()}>Next</button>
          </div>

          <div {...api.getItemGroupProps()}>
            {carouselData.map((image, index) => (
              <div {...api.getItemProps({ index })} key={index}>
                <img src={image} alt="" width="188px" />
              </div>
            ))}
          </div>
          <div {...api.getIndicatorGroupProps()}>
            {api.pageSnapPoints.map((_, index) => (
              <button {...api.getIndicatorProps({ index })} key={index} />
            ))}
          </div>
        </div>
      </main>

      <Toolbar controls={controls.ui}>
        <StateVisualizer state={service} omit={["translations"]} />
      </Toolbar>
    </>
  )
}

// examples/svelte-ts/src/routes/carousel.svelte
<script lang="ts">
  import StateVisualizer from "$lib/components/state-visualizer.svelte"
  import Toolbar from "$lib/components/toolbar.svelte"
  import { useControls } from "$lib/use-controls.svelte"
  import * as carousel from "@zag-js/carousel"
  import { carouselControls, carouselData } from "@zag-js/shared"
  import { normalizeProps, useMachine } from "@zag-js/svelte"

  const controls = useControls(carouselControls)

  const service = useMachine(carousel.machine, () => ({
    ...controls.context,
    id: "1",
    slideCount: carouselData.length,
  }))

  const api = $derived(carousel.connect(service, normalizeProps))
</script>

<main class="carousel">
  <div {...api.getRootProps()}>
    <button onclick={() => api.scrollToIndex(4)}>Scroll to 4</button>
    <div {...api.getControlProps()}>
      <button {...api.getAutoplayTriggerProps()}>{api.isPlaying ? "Stop" : "Play"}</button>
      <div class="carousel-spacer"></div>
      <button {...api.getPrevTriggerProps()}>Prev</button>
      <button {...api.getNextTriggerProps()}>Next</button>
    </div>

    <div {...api.getItemGroupProps()}>
      {#each carouselData as image, index}
        <div {...api.getItemProps({ index })}>
          <img src={image} alt="" />
        </div>
      {/each}
    </div>
    <div {...api.getIndicatorGroupProps()}>
      {#each api.pageSnapPoints as _, index}
        <!-- svelte-ignore a11y_consider_explicit_label -->
        <button {...api.getIndicatorProps({ index })}></button>
      {/each}
    </div>
  </div>
</main>

<Toolbar {controls}>
  <StateVisualizer state={service} />
</Toolbar>
