// examples/solid-ts/src/routes/checkbox.tsx
import * as checkbox from "@zag-js/checkbox"
import { checkboxControls } from "@zag-js/shared"
import { normalizeProps, useMachine } from "@zag-js/solid"
import serialize from "form-serialize"
import { createMemo, createUniqueId } from "solid-js"
import { StateVisualizer } from "~/components/state-visualizer"
import { Toolbar } from "~/components/toolbar"
import { useControls } from "~/hooks/use-controls"

export default function Page() {
  const controls = useControls(checkboxControls)
  const service = useMachine(checkbox.machine, () => ({ ...controls.state(), id: createUniqueId(), name: "checkbox" }))
  const api = createMemo(() => checkbox.connect(service, normalizeProps))

  return (
    <>
      <main class="checkbox">
        <pre>{JSON.stringify(service.prop("id"), null, 2)}</pre>
        <form
          onChange={(e) => {
            const formData = serialize(e.currentTarget, { hash: true })
            console.log(formData)
          }}
        >
          <fieldset>
            <fieldset>
              <label {...api().getRootProps()}>
                <div {...api().getControlProps()} />
                <span {...api().getLabelProps()}>Input {api().checked ? "Checked" : "Unchecked"}</span>
                <input {...api().getHiddenInputProps()} data-testid="hidden-input" />
                <div {...api().getIndicatorProps()}>Indicator</div>
              </label>
            </fieldset>

            <div>
              <button type="button" disabled={api().checked} onClick={() => api().setChecked(true)}>
                Check
              </button>
              <button type="button" disabled={!api().checked} onClick={() => api().setChecked(false)}>
                Uncheck
              </button>
              <button type="reset">Reset Form</button>
            </div>
          </fieldset>
        </form>
      </main>

      <Toolbar controls={controls}>
        <StateVisualizer state={service} />
      </Toolbar>
    </>
  )
}

// examples/svelte-ts/src/routes/checkbox.svelte
<script lang="ts">
  import StateVisualizer from "$lib/components/state-visualizer.svelte"
  import Toolbar from "$lib/components/toolbar.svelte"
  import { useControls } from "$lib/use-controls.svelte"
  import * as checkbox from "@zag-js/checkbox"
  import { checkboxControls } from "@zag-js/shared"
  import { normalizeProps, useMachine } from "@zag-js/svelte"
  import serialize from "form-serialize"

  const controls = useControls(checkboxControls)

  const service = useMachine(checkbox.machine, () => ({ ...controls.context, id: "1" }))

  const api = $derived(checkbox.connect(service, normalizeProps))
</script>

<main class="checkbox">
  <form
    oninput={(e) => {
      const result = serialize(e.currentTarget, { hash: true })
      console.log(result)
    }}
  >
    <fieldset>
      <label {...api.getRootProps()}>
        <div {...api.getControlProps()}></div>
        <span {...api.getLabelProps()}>Input {api.checked ? "Checked" : "Unchecked"}</span>
        <input {...api.getHiddenInputProps()} data-testid="hidden-input" />
        <div {...api.getIndicatorProps()}>Indicator</div>
      </label>

      <button type="button" disabled={api.checked} onclick={() => api.setChecked(true)}>Check</button>
      <button type="button" disabled={!api.checked} onclick={() => api.setChecked(false)}>Uncheck</button>
      <button type="reset">Reset Form</button>
    </fieldset>
  </form>
</main>

<Toolbar {controls}>
  <StateVisualizer state={service} />
</Toolbar>
