// examples/solid-ts/src/routes/clipboard.tsx
import * as clipboard from "@zag-js/clipboard"
import { clipboardControls } from "@zag-js/shared"
import { normalizeProps, useMachine } from "@zag-js/solid"
import { ClipboardCheck, ClipboardCopyIcon } from "lucide-solid"
import { Show, createMemo, createUniqueId } from "solid-js"
import { StateVisualizer } from "~/components/state-visualizer"
import { Toolbar } from "~/components/toolbar"
import { useControls } from "~/hooks/use-controls"

export default function Page() {
  const controls = useControls(clipboardControls)

  const service = useMachine(clipboard.machine, () => ({
    id: createUniqueId(),
    value: "https://github.com/chakra-ui/zag",
    ...controls.state(),
  }))

  const api = createMemo(() => clipboard.connect(service, normalizeProps))

  return (
    <>
      <main class="clipboard">
        <div {...api().getRootProps()}>
          <label {...api().getLabelProps()}>Copy this link</label>
          <div {...api().getControlProps()}>
            <input {...api().getInputProps()} style={{ width: "100%" }} />
            <button {...api().getTriggerProps()}>
              <Show when={api().copied} fallback={<ClipboardCopyIcon />}>
                <ClipboardCheck />
              </Show>
            </button>
          </div>
          <div {...api().getIndicatorProps({ copied: true })}>Copied!</div>
          <div {...api().getIndicatorProps({ copied: false })}>Copy</div>
        </div>
      </main>

      <Toolbar controls={controls}>
        <StateVisualizer state={service} />
      </Toolbar>
    </>
  )
}

// examples/svelte-ts/src/routes/clipboard.svelte
<script lang="ts">
  import StateVisualizer from "$lib/components/state-visualizer.svelte"
  import Toolbar from "$lib/components/toolbar.svelte"
  import { useControls } from "$lib/use-controls.svelte"
  import * as clipboard from "@zag-js/clipboard"
  import { clipboardControls } from "@zag-js/shared"
  import { normalizeProps, useMachine } from "@zag-js/svelte"
  import { ClipboardCheckIcon, ClipboardCopyIcon } from "lucide-svelte"

  const controls = useControls(clipboardControls)

  const service = useMachine(clipboard.machine, () => ({
    ...controls.context,
    id: "1",
    defaultValue: "https://github/com/chakra-ui/zag",
  }))

  const api = $derived(clipboard.connect(service, normalizeProps))
</script>

<main class="clipboard">
  <div {...api.getRootProps()}>
    <!-- svelte-ignore a11y_label_has_associated_control -->
    <label {...api.getLabelProps()}>Copy this link</label>
    <div {...api.getControlProps()}>
      <input {...api.getInputProps()} />
      <button {...api.getTriggerProps()}>
        {#if api.copied}
          <ClipboardCheckIcon />
        {:else}
          <ClipboardCopyIcon />
        {/if}
      </button>
    </div>
    <div {...api.getIndicatorProps({ copied: true })}>Copied!</div>
    <div {...api.getIndicatorProps({ copied: false })}>Copy</div>
  </div>
</main>

<Toolbar {controls}>
  <StateVisualizer state={service} />
</Toolbar>
