// examples/solid-ts/src/routes/combobox.tsx
import * as combobox from "@zag-js/combobox"
import { comboboxControls, comboboxData } from "@zag-js/shared"
import { normalizeProps, useMachine } from "@zag-js/solid"
import { XIcon } from "lucide-solid"
import { matchSorter } from "match-sorter"
import { Index, Show, createMemo, createSignal, createUniqueId } from "solid-js"
import { StateVisualizer } from "~/components/state-visualizer"
import { Toolbar } from "~/components/toolbar"
import { useControls } from "~/hooks/use-controls"

export default function Page() {
  const controls = useControls(comboboxControls)

  const [options, setOptions] = createSignal(comboboxData)

  const collection = createMemo(() =>
    combobox.collection({
      items: options(),
      itemToValue: (item) => item.code,
      itemToString: (item) => item.label,
    }),
  )

  const [value, setValue] = createSignal<string[]>([])

  const service = useMachine(combobox.machine, () => ({
    id: createUniqueId(),
    value: value(),
    onValueChange({ value }) {
      setValue(value)
    },
    collection: collection(),
    onOpenChange() {
      setOptions(comboboxData)
    },
    onInputValueChange({ inputValue }) {
      const filtered = matchSorter(comboboxData, inputValue, { keys: ["label"] })
      setOptions(filtered.length > 0 ? filtered : comboboxData)
    },
    ...controls.state(),
  }))

  const api = createMemo(() => combobox.connect(service, normalizeProps))

  return (
    <>
      <main class="combobox">
        <pre>{JSON.stringify(service.state.get(), null, 2)}</pre>
        <div>
          <button onClick={() => setValue(["TG"])}>Set to Togo</button>
          <button data-testid="clear-value-button" onClick={() => api().clearValue()}>
            Clear Value
          </button>
          <br />

          <div {...api().getRootProps()}>
            <label {...api().getLabelProps()}>Select country</label>
            <div {...api().getControlProps()}>
              <input data-testid="input" {...api().getInputProps()} />
              <button data-testid="trigger" {...api().getTriggerProps()}>
                ▼
              </button>
              <button {...api().getClearTriggerProps()}>
                <XIcon />
              </button>
            </div>
          </div>

          <div {...api().getPositionerProps()}>
            <Show when={options().length > 0}>
              <ul data-testid="combobox-content" {...api().getContentProps()}>
                <Index each={options()}>
                  {(item) => (
                    <li class="combobox__option" {...api().getItemProps({ item: item() })}>
                      {item().label}
                    </li>
                  )}
                </Index>
              </ul>
            </Show>
          </div>
        </div>
      </main>

      <Toolbar controls={controls}>
        <StateVisualizer state={service} omit={["collection"]} />
      </Toolbar>
    </>
  )
}

// examples/svelte-ts/src/routes/combobox.svelte
<script lang="ts">
  import StateVisualizer from "$lib/components/state-visualizer.svelte"
  import Toolbar from "$lib/components/toolbar.svelte"
  import { useControls } from "$lib/use-controls.svelte"
  import * as combobox from "@zag-js/combobox"
  import { comboboxControls, comboboxData } from "@zag-js/shared"
  import { normalizeProps, useMachine } from "@zag-js/svelte"
  import { matchSorter } from "match-sorter"

  const controls = useControls(comboboxControls)

  let options = $state.raw(comboboxData)

  const collection = $derived(
    combobox.collection({
      items: options,
      itemToValue: (item) => item.code,
      itemToString: (item) => item.label,
    }),
  )

  const service = $derived(
    useMachine(combobox.machine, () => ({
      ...controls.context,
      id: "1",
      get collection() {
        return collection
      },
      onOpenChange() {
        options = comboboxData
      },
      onInputValueChange({ inputValue }) {
        const filtered = matchSorter(comboboxData, inputValue, { keys: ["label"] })
        const newOptions = filtered.length > 0 ? filtered : comboboxData
        options = newOptions
      },
    })),
  )

  const api = $derived(combobox.connect(service, normalizeProps))
</script>

<main class="combobox">
  <div>
    <button onclick={() => api.setValue(["TG"])}>Set to Togo</button>
    <button data-testid="clear-value-button" onclick={() => api.clearValue()}> Clear Value </button>
    <br />
    <div {...api.getRootProps()}>
      <!-- svelte-ignore a11y_label_has_associated_control -->
      <label {...api.getLabelProps()}>Select country</label>
      <div {...api.getControlProps()}>
        <input data-testid="input" {...api.getInputProps()} />
        <button data-testid="trigger" {...api.getTriggerProps()}> ▼ </button>
      </div>
    </div>
    <div {...api.getPositionerProps()}>
      {#if options.length > 0}
        <ul data-testid="combobox-content" {...api.getContentProps()}>
          {#each options as item}
            <li data-testid={item.code} {...api.getItemProps({ item })}>
              {item.label}
            </li>
          {/each}
        </ul>
      {/if}
    </div>
  </div>
</main>

<Toolbar {controls}>
  <StateVisualizer state={service} />
</Toolbar>
