// examples/svelte-ts/src/routes/angle-slider.svelte
<script lang="ts">
  import StateVisualizer from "$lib/components/state-visualizer.svelte"
  import Toolbar from "$lib/components/toolbar.svelte"
  import { useControls } from "$lib/use-controls.svelte"
  import * as angleSlider from "@zag-js/angle-slider"
  import { angleSliderControls } from "@zag-js/shared"
  import { normalizeProps, useMachine } from "@zag-js/svelte"

  const controls = useControls(angleSliderControls)

  const service = useMachine(angleSlider.machine, () => ({ ...controls.context, id: "1" }))

  const api = $derived(angleSlider.connect(service, normalizeProps))
</script>

<main class="angle-slider">
  <div {...api.getRootProps()}>
    <!-- svelte-ignore a11y_label_has_associated_control -->
    <label {...api.getLabelProps()}>
      Angle Slider: <div {...api.getValueTextProps()}>{api.valueAsDegree}</div>
    </label>
    <div {...api.getControlProps()}>
      <div {...api.getThumbProps()}></div>
      <div {...api.getMarkerGroupProps()}>
        {#each [0, 45, 90, 135, 180, 225, 270, 315] as value}
          <div {...api.getMarkerProps({ value })}></div>
        {/each}
      </div>
    </div>
    <input {...api.getHiddenInputProps()} />
  </div>
</main>

<Toolbar {controls}>
  <StateVisualizer state={service} />
</Toolbar>

// examples/solid-ts/src/routes/angle-slider.tsx
import * as angleSlider from "@zag-js/angle-slider"
import { normalizeProps, useMachine } from "@zag-js/solid"
import { createMemo, createUniqueId, Index } from "solid-js"
import { angleSliderControls } from "@zag-js/shared"
import { StateVisualizer } from "../components/state-visualizer"
import { Toolbar } from "../components/toolbar"
import { useControls } from "../hooks/use-controls"

export default function Page() {
  const controls = useControls(angleSliderControls)
  const service = useMachine(angleSlider.machine, () => ({ ...controls.state(), id: createUniqueId() }))
  const api = createMemo(() => angleSlider.connect(service, normalizeProps))

  return (
    <>
      <main class="angle-slider">
        <div {...api().getRootProps()}>
          <label {...api().getLabelProps()}>
            Angle Slider: <div {...api().getValueTextProps()}>{api().valueAsDegree}</div>
          </label>
          <div {...api().getControlProps()}>
            <div {...api().getThumbProps()}></div>
            <div {...api().getMarkerGroupProps()}>
              <Index each={[0, 45, 90, 135, 180, 225, 270, 315]}>
                {(value) => <div {...api().getMarkerProps({ value: value() })}></div>}
              </Index>
            </div>
          </div>
          <input {...api().getHiddenInputProps()} />
        </div>
      </main>

      <Toolbar controls={controls}>
        <StateVisualizer state={service} />
      </Toolbar>
    </>
  )
}
