// examples/next-ts/pages/carousel.tsx
import * as carousel from "@zag-js/carousel"
import { normalizeProps, useMachine } from "@zag-js/react"
import { carouselControls, carouselData } from "@zag-js/shared"
import { useId } from "react"
import { StateVisualizer } from "../components/state-visualizer"
import { Toolbar } from "../components/toolbar"
import { useControls } from "../hooks/use-controls"

export default function Page() {
  const controls = useControls(carouselControls)

  const service = useMachine(carousel.machine, {
    id: useId(),
    slideCount: carouselData.length,
    ...controls.context,
  })

  const api = carousel.connect(service, normalizeProps)

  return (
    <>
      <main className="carousel">
        <div {...api.getRootProps()}>
          <button onClick={() => api.scrollToIndex(4)}>Scroll to 4</button>
          <div {...api.getControlProps()}>
            <button {...api.getAutoplayTriggerProps()}>{api.isPlaying ? "Stop" : "Play"}</button>
            <div className="carousel-spacer" />
            <button {...api.getPrevTriggerProps()}>Prev</button>
            <button {...api.getNextTriggerProps()}>Next</button>
          </div>

          <div {...api.getItemGroupProps()}>
            {carouselData.map((image, index) => (
              <div {...api.getItemProps({ index })} key={index}>
                <img src={image} alt="" width="188px" />
              </div>
            ))}
          </div>
          <div {...api.getIndicatorGroupProps()}>
            {api.pageSnapPoints.map((_, index) => (
              <button {...api.getIndicatorProps({ index })} key={index} />
            ))}
          </div>
        </div>
      </main>

      <Toolbar controls={controls.ui}>
        <StateVisualizer state={service} omit={["translations"]} />
      </Toolbar>
    </>
  )
}

// examples/solid-ts/src/routes/carousel.tsx
import * as carousel from "@zag-js/carousel"
import { carouselControls, carouselData } from "@zag-js/shared"
import { normalizeProps, useMachine } from "@zag-js/solid"
import { Index, Show, createMemo, createUniqueId } from "solid-js"
import { StateVisualizer } from "~/components/state-visualizer"
import { Toolbar } from "~/components/toolbar"
import { useControls } from "~/hooks/use-controls"

export default function Page() {
  const controls = useControls(carouselControls)

  const service = useMachine(carousel.machine, () => ({
    ...controls.state(),
    id: createUniqueId(),
    slideCount: carouselData.length,
  }))

  const api = createMemo(() => carousel.connect(service, normalizeProps))

  return (
    <>
      <main class="carousel">
        <div {...api().getRootProps()}>
          <button onClick={() => api().scrollToIndex(4)}>Scroll to 4</button>
          <div {...api().getControlProps()}>
            <button {...api().getAutoplayTriggerProps()}>
              <Show when={api().isPlaying} fallback="Play">
                Stop
              </Show>
            </button>
            <div class="carousel-spacer" />
            <button {...api().getPrevTriggerProps()}>Prev</button>
            <button {...api().getNextTriggerProps()}>Next</button>
          </div>
          <div {...api().getItemGroupProps()}>
            <Index each={carouselData}>
              {(image, index) => (
                <div {...api().getItemProps({ index })}>
                  <img src={image()} alt="" />
                </div>
              )}
            </Index>
          </div>

          <div {...api().getIndicatorGroupProps()}>
            <Index each={api().pageSnapPoints}>
              {(_, index) => <button {...api().getIndicatorProps({ index })} />}
            </Index>
          </div>
        </div>
      </main>

      <Toolbar controls={controls}>
        <StateVisualizer state={service} />
      </Toolbar>
    </>
  )
}
