// examples/next-ts/pages/signature-pad.tsx
import { normalizeProps, useMachine } from "@zag-js/react"
import { signaturePadControls } from "@zag-js/shared"
import * as signaturePad from "@zag-js/signature-pad"
import { RotateCcw } from "lucide-react"
import { useId, useState } from "react"
import { StateVisualizer } from "../components/state-visualizer"
import { Toolbar } from "../components/toolbar"
import { useControls } from "../hooks/use-controls"

export default function Page() {
  const [url, setUrl] = useState("")

  const controls = useControls(signaturePadControls)

  const service = useMachine(signaturePad.machine, {
    id: useId(),
    onDrawEnd(details) {
      details.getDataUrl("image/png").then(setUrl)
    },
    ...controls.context,
  })

  const api = signaturePad.connect(service, normalizeProps)

  return (
    <>
      <main className="signature-pad">
        <div {...api.getRootProps()}>
          <input {...api.getHiddenInputProps({ value: url })} />
          <label {...api.getLabelProps()}>Signature Pad</label>

          <div {...api.getControlProps()}>
            <svg {...api.getSegmentProps()}>
              {api.paths.map((path, i) => (
                <path key={i} {...api.getSegmentPathProps({ path })} />
              ))}
              {api.currentPath && <path {...api.getSegmentPathProps({ path: api.currentPath })} />}
            </svg>

            <div {...api.getGuideProps()} />
          </div>

          <button {...api.getClearTriggerProps()}>
            <RotateCcw />
          </button>
        </div>

        <button
          onClick={() => {
            api.getDataUrl("image/png").then(setUrl)
          }}
        >
          Show Image
        </button>
        {url && <img data-part="preview" alt="signature" src={url} />}
      </main>

      <Toolbar controls={controls.ui}>
        <StateVisualizer state={service} omit={["currentPoints", "currentPath", "paths"]} />
      </Toolbar>
    </>
  )
}

// examples/solid-ts/src/routes/signature-pad.tsx
import { signaturePadControls } from "@zag-js/shared"
import * as signaturePad from "@zag-js/signature-pad"
import { normalizeProps, useMachine } from "@zag-js/solid"
import { RotateCcw } from "lucide-solid"
import { For, Show, createMemo, createSignal, createUniqueId } from "solid-js"
import { StateVisualizer } from "~/components/state-visualizer"
import { Toolbar } from "~/components/toolbar"
import { useControls } from "~/hooks/use-controls"

export default function Page() {
  const [url, setUrl] = createSignal("")

  const controls = useControls(signaturePadControls)

  const service = useMachine(signaturePad.machine, () => ({
    id: createUniqueId(),
    onDrawEnd(details) {
      details.getDataUrl("image/png").then(setUrl)
    },
    ...controls.state(),
  }))

  const api = createMemo(() => signaturePad.connect(service, normalizeProps))

  return (
    <>
      <main class="signature-pad">
        <div {...api().getRootProps()}>
          <label {...api().getLabelProps()}>Signature Pad</label>

          <div {...api().getControlProps()}>
            <svg {...api().getSegmentProps()}>
              <For each={api().paths}>{(path) => <path {...api().getSegmentPathProps({ path })} />}</For>
              <Show when={api().currentPath}>
                {(path) => <path {...api().getSegmentPathProps({ path: path() })} />}
              </Show>
            </svg>
            <div {...api().getGuideProps()} />
          </div>

          <button {...api().getClearTriggerProps()}>
            <RotateCcw />
          </button>
        </div>

        <button
          onClick={() => {
            api().getDataUrl("image/png").then(setUrl)
          }}
        >
          Show Image
        </button>

        <Show when={url()}>
          <img data-part="preview" alt="signature" src={url()} />
        </Show>
      </main>

      <Toolbar controls={controls}>
        <StateVisualizer state={service} omit={["currentPoints", "currentPath", "paths"]} />
      </Toolbar>
    </>
  )
}
