// examples/next-ts/hooks/controls-context.tsx
import { PathOf, TypeAt } from "@zag-js/shared"
import { createContext, ProviderProps, useContext } from "react"

type ControlsContextValue<T> = {
  state: T
  setValue: (path: PathOf<T>, value: TypeAt<T, PathOf<T>>) => void
}

const ControlsContext = createContext<ControlsContextValue<any>>(undefined)

export function ControlsProvider<T>(props: ProviderProps<ControlsContextValue<T>>) {
  return <ControlsContext.Provider {...props} />
}

export function useControlsContext<T>() {
  const context = useContext<ControlsContextValue<T>>(ControlsContext)
  if (!context) throw new Error("No context provided")
  return context
}

// examples/solid-ts/src/hooks/controls-context.tsx
import { createContext, useContext, ParentProps } from "solid-js"

type ControlContextValue<T> = {
  state: T
  setValue: <V>(path: string, value: V) => void
}

const ControlContext = createContext<ControlContextValue<any>>(undefined)

export function ControlProvider<T>(props: ParentProps<{ value: ControlContextValue<T> }>) {
  return <ControlContext.Provider value={props.value}>{props.children}</ControlContext.Provider>
}

export function useControlContext<T>() {
  const context = useContext(ControlContext) as ControlContextValue<T>
  if (!context) throw new Error("No context provided")
  return context
}
