// examples/svelte-ts/src/lib/components/toolbar.svelte
<script lang="ts" generics="T">
  import type { UseControlsReturn } from "$lib/use-controls.svelte"
  import { dataAttr } from "@zag-js/dom-query"
  import Controls from "./controls.svelte"
  import type { Snippet } from "svelte"

  interface Props {
    controls?: UseControlsReturn<T> | null
    viz?: boolean
    children: Snippet
  }

  const { controls = $bindable(), viz, children }: Props = $props()

  let active = $state(viz ? 1 : !controls ? 1 : 0)
</script>

<div class="toolbar">
  <nav>
    {#if controls}
      <button data-active={dataAttr(active === 0)} onclick={() => (active = 0)}>Controls</button>
    {/if}
    <button data-active={dataAttr(active === 1)} onclick={() => (active = 1)}>Visualizer</button>
  </nav>
  {#if controls}
    <div data-content data-active={dataAttr(active === 0)}>
      <Controls {...controls} />
    </div>
  {/if}
  <div data-content data-active={dataAttr(active === 1)}>
    {@render children()}
  </div>
</div>

// examples/solid-ts/src/components/toolbar.tsx
import { dataAttr } from "@zag-js/dom-query"
import { createSignal, JSX, Show } from "solid-js"
import { UseControlsReturn } from "~/hooks/use-controls"
import { Controls } from "./controls"

export function Toolbar<T extends object>(props: {
  controls?: UseControlsReturn<T> | null
  children?: JSX.Element
  viz?: boolean
}) {
  const [active, setActive] = createSignal(props.viz ? 1 : !props.controls ? 1 : 0)

  return (
    <div class="toolbar">
      <nav>
        <Show when={props.controls}>
          <button data-active={dataAttr(active() === 0)} onClick={() => setActive(0)}>
            Controls
          </button>
        </Show>
        <button data-active={dataAttr(active() === 1)} onClick={() => setActive(1)}>
          Visualizer
        </button>
      </nav>
      <div>
        <Show when={props.controls}>
          {(controls) => (
            <div data-content data-active={dataAttr(active() === 0)}>
              <Controls store={controls()} />
            </div>
          )}
        </Show>
        <div data-content data-active={dataAttr(active() === 1)}>
          {props.children}
        </div>
      </div>
    </div>
  )
}
